services:
  postgres:
    image: postgres:15
    env_file:
      - .env
      - .env.development
    ports:
      - "5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  solr:
    build: ./solr
    ports:
      - "8983:8983"
    environment:
      - SOLR_HEAP=4g
      - SOLR_HOME=/solr_home
      - SOLR_CONFIG_DIR=/solr_conf
    volumes:
      - solr:/solr_home

  web:
    build:
      context: .
      target: web
      # cache_from:
      #   - "${REGISTRY_HOST}${REGISTRY_URI}/oral-history:${TAG}"
    image: "${REGISTRY_HOST}${REGISTRY_URI}/oral-history:${TAG}"
    env_file:
      - .env
      - .env.development
    volumes:
      - .:/home/app/webapp
    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as byebug, etc:
    stdin_open: true
    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true
    # ports:
    #   - "${DOCKER_PORTS}"
    #   - "8000:80"
    environment:
      - VIRTUAL_HOST=oralhistory.test
      - VIRTUAL_PORT=80
    depends_on:
      - postgres
      - solr
      - worker

  worker:
    build:
      context: .
      target: web
      # cache_from:
      #   - "${REGISTRY_HOST}${REGISTRY_URI}/oral-history:${TAG}"
    env_file:
      - .env
      - .env.development
    volumes:
      - .:/home/app/webapp
    command: ["sh", "-c", "bundle exec rails db:migrate && bin/delayed_job run"]
    depends_on:
      - postgres
      - solr

volumes:
  postgres:
  solr:
